### ISSUE TITLE
Fatal error:  Uncaught Exception: Parser not found.

### ISSUE THREAD

**Issue by joelemanoel** [LoginovIlya/php-psd-enginedata#1]
PHP Fatal error:  Uncaught Exception: Parser not found. Line: 1 in C:\Users\Administrator\Desktop\teste\vendor\loginovilya\php-psd-enginedata\src\Enginedata.php:69

file_get_contents is works.

index.php code:
```
<?php

require "vendor/autoload.php";

use Enginedata\Enginedata;

$data = file_get_contents('test.psd');
$parser = new Enginedata($data);

$data = $parser->parse();

var_dump($data);
?>
```

**Comment by LoginovIlia** [comment]
Hello. You are trying to parse a psd file. This library works with 'EngineData'. This format is only part of the psd file.

**Comment by joelemanoel** [comment]
Ok, thanks @LoginovIlya
